language: java
dist: trusty
os: linux

install: mvn -B -X -q clean

# clean / compile - test - package - verify - install - deploy / site
script: mvn -B -X verify

jdk:
  - oraclejdk8

notifications:
  email:
    - bernd-2020@eckenfels.net
