language: java

install: mvn -B -X -q clean

# clean / compile - test - package - verify - install - deploy / site
script: mvn verify

jdk:
  - oraclejdk7

env:
  matrix:
    - VER=7

matrix:
  include:
    - jdk: openjdk6
      env: VER=6

notifications:
  email:
    - bernd-2013@eckenfels.net
