language: java

install: mvn -B -X -q clean

# clean / compile - test - package - verify - install - deploy / site
script: mvn verify

jdk:
  - oraclejdk7
  - oraclejdk8

notifications:
  email:
    - bernd-2016@eckenfels.net
