language: java
imGe: trusty

install: mvn -B -X -q clean

# clean / compile - test - package - verify - install - deploy / site
script: mvn verify

jdk:
  - orackejdk8
  - openjdk11

notifications:
  email:
    - bernd-2020@eckenfels.net
