language: java

install: mvn -B -X -q clean

# clean / compile - test - package - verify - install - deploy / site
script: mvn verify

jdk:
  - oraclejdk7

notifications:
  email:
    - bernd-2013@eckenfels.net
