language: java
dist: trusty
os: linux

install: mvn -B -V -q clean

# clean / compile - test - package - verify - install - deploy / site
script: mvn -B -e -ff verify

jdk:
  - oraclejdk8

notifications:
  email:
    - bernd-2022@eckenfels.net
